// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGit_9hsautuneXHND38Un5EW5GllxU5U',
    appId: '1:610587226212:web:eef5c6e762e93877ae2f71',
    messagingSenderId: '610587226212',
    projectId: 'trustlocal-f3743',
    authDomain: 'trustlocal-f3743.firebaseapp.com',
    storageBucket: 'trustlocal-f3743.firebasestorage.app',
    measurementId: 'G-M157RL1DGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChruKw0YXXwz9see-yyt_wGbiO3-mwfDo',
    appId: '1:610587226212:android:0542bd9d77e4582bae2f71',
    messagingSenderId: '610587226212',
    projectId: 'trustlocal-f3743',
    storageBucket: 'trustlocal-f3743.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ5QCOXjcZvc2fdhN7sY4uDkpm9VNh9cg',
    appId: '1:610587226212:ios:77a05c8a35ad18ceae2f71',
    messagingSenderId: '610587226212',
    projectId: 'trustlocal-f3743',
    storageBucket: 'trustlocal-f3743.firebasestorage.app',
    iosBundleId: 'com.example.trustlocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ5QCOXjcZvc2fdhN7sY4uDkpm9VNh9cg',
    appId: '1:610587226212:ios:77a05c8a35ad18ceae2f71',
    messagingSenderId: '610587226212',
    projectId: 'trustlocal-f3743',
    storageBucket: 'trustlocal-f3743.firebasestorage.app',
    iosBundleId: 'com.example.trustlocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGit_9hsautuneXHND38Un5EW5GllxU5U',
    appId: '1:610587226212:web:1674d858be55ccd3ae2f71',
    messagingSenderId: '610587226212',
    projectId: 'trustlocal-f3743',
    authDomain: 'trustlocal-f3743.firebaseapp.com',
    storageBucket: 'trustlocal-f3743.firebasestorage.app',
    measurementId: 'G-K8444HJW39',
  );
}
