"""
Pydantic schemas package for KhedmaLink backend
Contains Pydantic models for request/response validation
"""

from .auth import (
    UserRegister,
    UserLogin,
    TokenResponse,
    TokenRefresh,
    UserResponse,
    UserUpdate,
    PasswordChange,
    RoleResponse,
    RoleAssignment,
    VerificationRequest,
)
from .provider import (
    CategoryCreate,
    CategoryUpdate,
    CategoryResponse,
    ProviderProfileCreate,
    ProviderProfileUpdate,
    ProviderProfileResponse,
    ProviderProfilePublic,
    ProviderServiceCreate,
    ProviderServiceUpdate,
    ProviderServiceResponse,
    ServiceAreaCreate,
    ServiceAreaUpdate,
    ServiceAreaResponse,
    AvailabilityRuleCreate,
    AvailabilityRuleUpdate,
    AvailabilityRuleResponse,
    VerificationCaseCreate,
    VerificationCaseResponse,
    VerificationCaseAdminUpdate,
)

__all__ = [
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "TokenRefresh",
    "UserResponse",
    "UserUpdate",
    "PasswordChange",
    "RoleResponse",
    "RoleAssignment",
    "VerificationRequest",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "ProviderProfileCreate",
    "ProviderProfileUpdate",
    "ProviderProfileResponse",
    "ProviderProfilePublic",
    "ProviderServiceCreate",
    "ProviderServiceUpdate",
    "ProviderServiceResponse",
    "ServiceAreaCreate",
    "ServiceAreaUpdate",
    "ServiceAreaResponse",
    "AvailabilityRuleCreate",
    "AvailabilityRuleUpdate",
    "AvailabilityRuleResponse",
    "VerificationCaseCreate",
    "VerificationCaseResponse",
    "VerificationCaseAdminUpdate",
]
